trigger:
  branches:
    include: ['main','dev']

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: UseNode@1
      inputs:
        version: '16.x'
    - script: |
        echo "Build step placeholder"
      displayName: 'Build'

- stage: Test
  dependsOn: Build
  jobs:
  - job: Tests
    steps:
    - script: |
        echo "Run unit tests placeholder"
      displayName: 'Run tests'
